from django.shortcuts import render
from .models import employee
# Create your views here.

def emplist(request):
    emp = employee.objects.all().values()
    print(emp)
    return render(request,'employee/empList.html',{"emp":emp})

def empFilter(request):
    #select * from employee where empname=kashish
    empname = employee.objects.filter(empName="Kashish").values()
    print(empname)
    empcity = employee.objects.filter(empCity='Ahmedabad').values()
    print(empcity)
    empgender = employee.objects.filter(empGender='female').values()
    print(empgender)
    empcitydesi = employee.objects.filter(empSalary__gte=50000,empDesignation='Developer')
    print(empcitydesi)
    empage = employee.objects.filter(empAge__gt=20).values()
    print(empage)
    empsadedep = employee.objects.filter(empSalary__gte=50000,empDesignation='Developer')
    print(empsadedep)
    empsalary = employee.objects.order_by('empSalary').values()
    print(empsalary)
    empsalary1 = employee.objects.order_by('-empSalary').values()
    print(empsalary1)
    emppost = employee.objects.filter(empDepartment='Development')
    print(emppost)
    empdesi = employee.objects.filter(empDesignation='Developer')
    print(empdesi)
    emppost1 = employee.objects.filter(empDepartment__exact='development')
    emppost2 = employee.objects.filter(empDepartment__iexact='Development')
    print(emppost1)
    print(emppost2)
    empname1 = employee.objects.filter(empName__contains='A')
    empname2 = employee.objects.filter(empName__icontains='a')
    print(empname1)
    print(empname2)
    employee10 = employee.objects.filter(empName__startswith="k").values()
    employee11 = employee.objects.filter(empName__endswith="l").values()
    employee12 = employee.objects.filter(empName__istartswith="k").values()
    employee13 = employee.objects.filter(empName__iendswith="l").values()
    print(employee10)
    print(employee11)
    print(employee12)
    print(employee13)
    return render(request,'employee/empfilter.html',{"emp":empname})
