# Generated by Django 6.0.1 on 2026-02-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empName', models.CharField(max_length=100)),
                ('empSalary', models.IntegerField()),
                ('empDesignation', models.CharField(max_length=100)),
                ('empCity', models.CharField(max_length=50)),
                ('empEmail', models.EmailField(max_length=254)),
                ('empConatct', models.CharField(max_length=10)),
                ('empAge', models.IntegerField()),
                ('empJoiningDate', models.DateField(auto_now_add=True)),
                ('empDepartment', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
