# Generated by Django 6.0.1 on 2026-02-10 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Gender',
            new_name='empGender',
        ),
    ]
