# Generated by Django 6.0.1 on 2026-02-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_rename_gender_employee_empgender'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=50)),
                ('cFees', models.IntegerField()),
                ('CDuration', models.IntegerField(default=6)),
            ],
        ),
    ]
