# Generated by Django 6.0.1 on 2026-02-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='gymuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('userEmail', models.EmailField(max_length=254, null=True)),
                ('userPassword', models.CharField(max_length=100)),
                ('userPhone', models.CharField(max_length=15, null=True)),
                ('userAddress', models.TextField(null=True)),
            ],
            options={
                'db_table': 'GYMMember',
            },
        ),
    ]
