# Generated by Django 6.0.1 on 2026-02-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_gymuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toyname', models.CharField(max_length=100)),
                ('toycategory', models.CharField(max_length=50)),
                ('toyprice', models.IntegerField()),
                ('discount', models.IntegerField()),
            ],
            options={
                'db_table': 'Toys',
            },
        ),
    ]
