# Generated by Django 6.0.1 on 2026-02-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_toys'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='Course',
        ),
    ]
