# Generated by Django 6.0.1 on 2026-02-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_product_productcolor_product_productstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productDescription',
            field=models.TextField(null=True),
        ),
    ]
