# Generated by Django 6.0.1 on 2026-02-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_product_productdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(max_length=60)),
                ('carModel', models.IntegerField(max_length=4)),
                ('carDescription', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Car',
            },
        ),
    ]
