# Generated by Django 6.0.1 on 2026-02-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='carModel',
            new_name='carModelYear',
        ),
    ]
