# Generated by Django 6.0.1 on 2026-02-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_rename_carmodel_car_carmodelyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carFeatures',
            field=models.TextField(null=True),
        ),
    ]
