# Generated by Django 6.0.1 on 2026-02-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_car_carfeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carModelDate',
            field=models.DateField(null=True),
        ),
    ]
