# Generated by Django 6.0.1 on 2026-02-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_car_carmodeldate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='carModelDate',
            new_name='carBuyDate',
        ),
        migrations.AddField(
            model_name='car',
            name='carOwner',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='carPrice',
            field=models.IntegerField(null=True),
        ),
    ]
