# Generated by Django 6.0.1 on 2026-02-06 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_rename_carmodeldate_car_carbuydate_car_carowner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='gymuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('userEmail', models.EmailField(max_length=254, null=True)),
                ('userPassword', models.CharField(max_length=100)),
                ('userPhone', models.CharField(max_length=15, null=True)),
                ('userAddress', models.TextField(null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='gymuserprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodytype', models.CharField(choices=[('Ectomorph', 'Ectomorph'), ('Mesomorph', 'Mesomorph'), ('Endomorph', 'Endomorph')], max_length=50)),
                ('dateOfBirth', models.DateField(null=True)),
                ('workouttime', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=50)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.gymuser')),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
    ]
