# Generated by Django 6.0.1 on 2026-02-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_gymuser_gymuserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='carModelYear',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='gymuser',
            table='GYMUser',
        ),
        migrations.AlterModelTable(
            name='gymuserprofile',
            table='GYMUserProfile',
        ),
    ]
