# Generated by Django 6.0.1 on 2026-02-06 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_car_carmodelyear_alter_gymuser_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'GYM City',
            },
        ),
        migrations.CreateModel(
            name='gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gymName', models.CharField(max_length=100)),
                ('gymLocation', models.CharField(max_length=100)),
                ('gymContact', models.CharField(max_length=15)),
                ('gymEmail', models.EmailField(max_length=254, null=True)),
                ('gymDescription', models.TextField(null=True)),
                ('cityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.city')),
            ],
            options={
                'db_table': 'GYM',
            },
        ),
    ]
