# Generated by Django 6.0.1 on 2026-02-06 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_city_gym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrainerName', models.CharField(max_length=50)),
                ('TrainerCity', models.CharField(max_length=50)),
                ('TrainerContact', models.CharField(max_length=10)),
                ('TrainerEmail', models.EmailField(max_length=254)),
                ('cityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.city')),
            ],
            options={
                'db_table': 'Trainer',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberName', models.CharField(max_length=50)),
                ('MemberCity', models.CharField(max_length=50)),
                ('MemberEmail', models.EmailField(max_length=254)),
                ('MemberContact', models.CharField(max_length=10)),
                ('MemberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.trainer')),
            ],
            options={
                'db_table': 'Member',
            },
        ),
    ]
